<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.bundle.min.js"></script>
<script src="https://s3.amazonaws.com/assets.blackbird.am/merlin-typeahead-3.0.1.min.js"></script>
<script>
    merlinTypeahead({
        selector: '#search',
        target:
        <?php
            echo    "'".
                    trim(Mage::getStoreConfig('merlinsearch/merlinconfig/company')).
                    ".".
                    trim(Mage::getStoreConfig('merlinsearch/merlinconfig/environment')).
                    ".".
                    trim(Mage::getStoreConfig('merlinsearch/merlinconfig/instance')).
                    "'";
        ?>
    });
    jQuery.noConflict();
</script>
